cc_library(
    name = 'threadpool',
    srcs = ['threadpool.cpp', ],
    hdrs = ['include/threadpool/threadpool.h', ],
    deps = ['//src/common:common'],
    strip_include_prefix = 'include',
    visibility = ["//visibility:public"],
)
