cc_library(
    name = 'common',
    srcs = ['src/fs_utils.cpp', ],
    hdrs = ['include/common/concurrent_queue.h',
            'include/common/foundation_types.h',
            'include/common/fs_utils.h',
            'include/common/idtable.h',
            'include/common/static_idtable.h',
            'include/common/string_utils.h',
           ],
    strip_include_prefix = 'include',
    visibility = ["//visibility:public"],
)
